// Generated by CoffeeScript 2.6.1
var Box, main, num, tmp, x;

import {
  t
} from "../main";

main = document.querySelector("#main");

Box = () => {
  return t().$style(() => {
    return {
      margin: "1rem",
      background: "#eee",
      border: "0.1rem solid #ccc",
      fontSize: "1.6rem"
    };
  }).$inner(() => {
    return "hello";
  });
};

num = 0;

x = null;

tmp = Box().$inner(() => {
  return [
    Box().$inner(() => {
      return "呜啊拉拉";
    }),
    Box().$inner(() => {
      return "呜啦啦啦";
    }),
    Box().$inner(() => {
      return "我是按钮" + num;
    }).$attr((i) => {
      return {
        onclick: () => {
          num++;
          return i.redraw();
        },
        oncreate: (dom) => {
          return dom.onmouseover = () => {
            return console.log(111);
          };
        }
      };
    })
  ];
}).mount(main);

console.log(tmp);
